Soal 1

In [6]:
nama = "Unique Scovi Egnel"
kode_mahasiswa = "20210801509"
mata_kuliah = "Machine Learning"

print("--------DATA DIRI--------")
print("Nama         : ", nama)
print("Kode Dosen   : ", kode_mahasiswa)
print("Perkuliahan  : ", mata_kuliah)

--------DATA DIRI--------
Nama         :  Unique Scovi Egnel
Kode Dosen   :  20210801509
Perkuliahan  :  Machine Learning


Soal 2

In [7]:
matriksC= [[1,2,3],[4,5,6]]
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


Soal 3

In [8]:
matriks = [[2,2],[2,2],[2,2]]
print(matriks)

[[2, 2], [2, 2], [2, 2]]


Soal 4

In [9]:
import numpy as np

Soal 5

In [10]:
from numpy import *
matriks = range(32)
matriks = reshape(matriks, (4,8))
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


Soal 6

In [11]:
import numpy as np
from numpy import *

matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[2 1 1 1 1 1 3 4 1 2 1 1 2 1 1 2 4 3 1 3 4 4 4 2 3 2 3 2 1 2]
 [4 1 1 4 3 2 3 3 4 3 3 4 1 2 1 3 2 2 3 2 3 3 4 2 2 2 2 3 2 3]
 [2 4 4 2 3 3 4 3 3 4 3 4 4 4 2 4 4 1 3 2 1 3 2 2 2 4 1 3 2 3]]
